workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
        environment:
          APP_SETTINGS: config.TestingConfig
          DATABASE_URL: postgresql://localhost/circle_test
          TEST_DATABASE_URL: postgresql://localhost/circle_test
      - image: circleci/postgres:9.5-alpine # database image
        environment: # environment variables for database
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python manage.py db upgrade
      - run:
          command: |
            . venv/bin/activate
            pytest -v --cov=consumeless tests/
  deploy:
    build:
      docker:
        - image: circleci/python:3.8.0
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/£HEROKU_APP_NAME.git master
