version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
      environment:
        APP_SETTINGS: config.DevelopmentConfig
      - image: circleci/postgres:9.5-alpine
    steps:
      - checkout
      - run:
        command: python3 -m venv venv
